name = "my-site"
defaultTargets = ["Home", "generate-site"]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso.git"
rev = "v4.29.0"

[[lean_lib]]
name = "Theme"
srcDir = "pages"

[[lean_lib]]
name = "Common"
srcDir = "pages"

[[lean_lib]]
name = "Home"
srcDir = "pages"

[[lean_lib]]
name = "Research"
srcDir = "pages"

[[lean_lib]]
name = "Defense"
srcDir = "pages"

[[lean_exe]]
name = "generate-site"
root = "Main"
